[[colors.indexed_colors]]
color = "#fe8019"
index = 16

[[colors.indexed_colors]]
color = "#d65d0e"
index = 17

[[colors.indexed_colors]]
color = "#3c3836"
index = 18

[[colors.indexed_colors]]
color = "#504945"
index = 19

[[colors.indexed_colors]]
color = "#bdae93"
index = 20

[[colors.indexed_colors]]
color = "#ebdbb2"
index = 21

[colors.bright]
black = "#665c54"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#fbf1c7"
yellow = "#fabd2f"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#1d2021"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#d5c4a1"
yellow = "#fabd2f"

[colors.primary]
background = "#1d2021"
foreground = "#d5c4a1"

[font]
size = 10.0

[font.normal]
family = "SauceCodePro NFM Medium"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "J"
mods = "Shift|Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "K"
mods = "Shift|Alt"

[scrolling]
history = 100000

[window]
opacity = 0.9
