-- -- File navigation hotkeys
-- vim.api.nvim_set_keymap('n', '<leader>jf', '<cmd>Files<CR>', {noremap = true})
-- vim.api.nvim_set_keymap('n', '<leader>jb', '<cmd>Buffers<CR>', {noremap = true})
-- 
-- vim.api.nvim_exec([[function! s:list_cmd()
--   let base = fnamemodify(expand('%'), ':h:.:S')
--   return base == '.' ? 'fd --type file --follow' : printf('fd --type file --fllow | proximity-sort %s', shellescape(expand('%')))
-- endfunction
-- 
-- command! -bang -nargs=? -complete=dir Files
--   \ call fzf#vim#files(<q-args>, {'source': s:list_cmd(),
--   \                               'options': '--tiebreak=index'}, <bang>0)
-- ]], false)
