#!/bin/sh

# Alias vim to nvim if present
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d" v="nvim"

# Common commands that are too long
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yta="youtube-dl -f best -icx --add-metadata" \
	yt="youtube-dl -f best -ic --add-metadata" \
	ffmpeg="ffmpeg -hide_banner"

# Add some colour
alias \
	grep="grep --color=auto" \
	diff="diff --color=auto"

# ls commands
if [ -x $(command -v exa) ]; then
	alias \
		l="exa" \
		ls="exa" \
		la="exa -a" \
		ll="exa -l" \
		lla="exa -la"

else
	alias \
		l="ls" \
		la="ls -a" \
		ll="ls -l" \
		lla="ls -la"
fi
# Some common commands
alias g="git"
alias gap="git add -p"
alias z="zathura"
alias p="paru"
alias e="$EDITOR"

alias sc="du -a ~/.local/bin/ | cut -f2 | fzf | xargs -r $EDITOR"
alias ralias="source ~/.config/zsh/aliasrc"
alias psearch="ps aux | grep -v grep | grep $1"
mkfilename() { 
	file="$1"
	ext="${file##*.}"
	name="$(echo "$file" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '_' | sed 's/-\+/-/g;s/\(^-\|-$\)//g')"
	echo "${name%$ext}.""$ext"
}
