#!/bin/sh

# Alias vim to nvim if present
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d" v="nvim"

# Common commands that are too long
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl -f best -ic --add-metadata" \
	yta="youtube-dl -f best -icx --add-metadata" \
	ytp="yt-dlp --download-archive ~/.config/yt/yt-dl-vid.conf" \
	ytap="yt-dlp -icx --add-metadata" \
	ffmpeg="ffmpeg -hide_banner" \
	xclipboard="xclip -selection clipboard"

# Remove these files from home directory
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"
alias netbeans=netbeans --userdir "${XDG_CONFIG_HOME}"/netbeans
alias monerod=monerod --data-dir "$XDG_DATA_HOME"/bitmonero

# Add some colour
alias \
	grep="grep --color=auto" \
	diff="diff --color=auto"

# ls commands
if [ -x $(command -v exa) ]; then
	alias \
		ls="exa --icons" \
		l="exa --icons" \
		la="exa -a --icons" \
		ll="exa -l --icons" \
		lla="exa -la --icons"

else
	alias \
		l="ls" \
		la="ls -a" \
		ll="ls -l" \
		lla="ls -la"
fi
# Some common commands
alias gap="git add -p"
alias gds="git diff --staged"

alias sudo="sudo "
alias sc="du -a ~/.local/bin/ | grep -v pip | cut -f2 | fzf | xargs -r $EDITOR"
alias ralias="source ~/.config/zsh/aliasrc"
alias psearch="ps aux | grep -v grep | grep $1"
alias opusedit="opustags --edit --in-place $1"
alias compat-ssh="TERM=rxvt-256color ssh"
alias mksnap="sudo btrfs subv snapshot /home "/home/@home-$(date +%Y%m%d-%H%M)""

# Aliases for yt-dlp
alias ytp-vid="yt-dlp --config-location ~/.config/yt/yt-dl-vid.conf "$@""
alias ytp-channel="yt-dlp --config-location ~/.config/yt/yt-dl-channel.conf "$@""
alias ytp-playlist="yt-dlp --config-location ~/.config/yt/yt-dl-playlist.conf "$@""
