#!/bin/sh

bspc rule -r "*"

nm-applet &
pgrep -x sxhkd || sxhkd &
setbg &
dunst &
pgrep -x lxsession || lxsession &
xrdb ~/.config/x11/xresources &
picom -b --experimental-backends &
flameshot &
xsetroot -cursor_name left_ptr &
xset -b &
pgrep -x imwheel || imwheel &
pgrep -x mpd || mpd &

[ -x ~/.local/bin/setkblayout ] && ~/.local/bin/setkblayout -l us &
[ -x ~/.config/bspwm/bspswallow ] && ~/.config/bspwm/bspswallow &
[ -x ~/.config/polybar/launch.sh ] && ~/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

toggleborder -n

bspc config focused_border_color \#ffb52a
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer false

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc rule -a sxiv state=floating center=true
bspc rule -a polybar border=off manage=off
bspc rule -a mpv state=fullscreen
