#!/bin/sh

bspc rule -r "*"

nm-applet &
sxhkd &
nitrogen --restore &
dunst &
[ -x ~/.config/polybar/launch.sh ] && ~/.config/polybar/launch.sh &
picom -b --experimental-backends &
flameshot &
fcitx -d &
xsetroot -cursor_name left_ptr &
setxkbmap -option compose:rctrl
xmodmap ~/.Xmodmap

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 5
bspc config top_padding 32
bspc config bottom_padding 5
bspc config left_padding 5
bspc config right_padding 5
bspc config focused_border_color \#3c3836
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc rule -a ulauncher focus=on
bspc rule -a sxiv state=floating center=true
bspc rule -a polybar border=off manage=off

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc rule -a mpv state=fullscreen
