#!/bin/sh

bspc rule -r "*"

nm-applet &
killall sxhkd
sxhkd &
setbg &
dunst &
killall lxsession
lxsession &
xrdb ~/.config/x11/xresources &
picom -b --experimental-backends &
flameshot &
fcitx -d &
xsetroot -cursor_name left_ptr &
xset -b &
[ -x ~/.local/bin/setxkbalyout ] && ~/.local/bin/setkblayout -s us &
[ -x ~/.config/bspwm/bspswallow ] && ~/.config/bspwm/bspswallow &
[ -x ~/.config/polybar/launch.sh ] && ~/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 3
bspc config top_padding 32
bspc config bottom_padding 5
bspc config left_padding 5
bspc config right_padding 5
bspc config focused_border_color \#ffb52a
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc rule -a sxiv state=floating center=true
bspc rule -a polybar border=off manage=off
bspc rule -a mpv state=fullscreen
bspc rule -a discord desktop='^10'
