[pyprland]
plugins = ["scratchpads", "magnify"]

[scratchpads.python]
animation = "fromTop"
command = "alacritty --class scratchpad -e python"
class = "scratchpad"
size = "35% 35%"
max_size = "75% 60%"
margin = 200

[scratchpads.qalc]
animation = "fromTop"
command = "alacritty --class scratchpad -e qalc"
class = "scratchpad"
size = "35% 35%"
max_size = "75% 60%"
margin = 200
